services:
  mysql:
    image: mysql:8
    container_name: memora-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Fiap2026}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-global_solution}
    volumes:
      - memora_mysql_data:/var/lib/mysql

volumes:
  memora_mysql_data:
